name: Strava Kudos

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          headless: true
          record: true
          install: false
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_STRAVA_USERNAME: ${{ secrets.CYPRESS_STRAVA_USERNAME }}
          CYPRESS_STRAVA_PW: ${{ secrets.CYPRESS_STRAVA_PW }}
          CYPRESS_STRAVA_ATHLETE_ID: ${{ secrets.CYPRESS_STRAVA_ATHLETE_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
